### ISSUE TITLE
Consider using definitions from 360Giving

### ISSUE THREAD

**Issue by mrshll1001** [ThreeSixtyGiving/360-dei#11]
There are two cases where the DEI schema implements features or structures already present in 360Giving:

* `DEI_Classification` defines the same structure as `Classification` from 360Giving
* `DEI_Answer/location` defines an array of objects which includes a single `description` field, resembling a cut-down `Location` definition

I believe we should be striving to reuse the components we have from 360Giving where possible to avoid bloat but also to make it easier for us to develop other Extensions in the future. This would lend itself to replacing all references to `DEI_Classification` to `Classification` and including a reference to `Location` at `DEI_Answer/location`.

One thing to note, though, is that the definitions/structures in the DEI Schema do actually include *additional constraints* when compared to their implementations in the 360Giving schema:

* `DEI_Classification` requires `vocabulary` and `code`
* `DEI_Answer/location` requires `description`

This could therefore be a deliberate design choice. We could add these additional constraints to the original definitions by means of this extension, but this would add the constraints to other instances of the `Classification` and `Location` definitions throughout the standard. It could be possible using JSONSchema to only include the new requirements at the locations defined in the DEI Schema, which might be preferable. I can investigate this.

**Comment by mrshll1001** [comment]
I'm experimenting with a ways to do this, as it is preferable to reuse definitions from the core standard where possible. [This commit](https://github.com/ThreeSixtyGiving/360-dei/commit/dc6457c797951fd07728684646b474ec05aea5e0) does the following where Classifications are used:

```json
{
"dei_classification_available_options": {
            "title": "Classifications from Taxonomies available options",
            "description": "Classifications from Taxonomies which were available when the question was asked?",
            "type": "array",
            "items": {
              "allOf": [
                {
                  "required": [
                    "vocabulary",
                    "code"
                  ]
                },
                {
                  "$ref": "#/definitions/Classification"
                }
              ]
            }
          }
}
```

It validates as JSON Schema. I will need to test this, but I believe the following logic is applied:

* on this property, each item of the array must be valid against BOTH the sub-schemas listed
* the first of these sub-schemas enforces the required properties of `vocabulary` and `code`
* the second of these states it needs to be  a valid `Classification` object.

If this achieves the desired effect, I will apply this in a new PR.

**Comment by kindly** [comment]
@mrshll1001 

I think this should work.

The only change I would definitely make is to just repeat {"type": "object"} next to the `required` as it is not clear from the specs if you are allowed to do a `required` without the type being `object`.

I am slightly concerned by the bad validation errors the above might cause. The only way round that would be something like:

```
{
"dei_classification_available_options": {
            "title": "Classifications from Taxonomies available options",
            "description": "Classifications from Taxonomies which were available when the question was asked?",
            "type": "array",
            "items": {
              "$ref": "#/definitions/Classification"
            }
            "allOf": [
              {
                "items": {
                  "type": "object",
                  "required": [
                    "vocabulary",
                    "code"
                  ]
                }

              ]
            }
          }
}
```

However, this is a bit more verbose and confusing to read.

**Comment by mrshll1001** [comment]
Thanks @kindly, definitely noted re the inclusion of type:object.

In your example, the `items` key is closed off before the `allOf` block. If the $ref replaces the object at that level, does that mean `allOf` still sits outside of that level?  Will this definitely be applied as a schema within the items block? 

EDIT: Scratch that. I see now, there's another `items` key. Will JSON Schema permit that there are two `items` keys?

**Comment by kindly** [comment]
@mrshll1001 
Yes, as far as I understand, it will validate each `allOf` as their own schema, validating data on that level, so you can repeat anything as much as you like.  However, as noted with the `{"type": "object"}` it does not merge the schemas, so each block in an `allOf` has to work on its own and not share anything with any other allOf block.

**Comment by mrshll1001** [comment]
Closing as irrelevant now we've moved to a different model
