### ISSUE TITLE
Why a question was not asked; when it was asked (askedStatus field)

### ISSUE THREAD

**Issue by ghost** [ThreeSixtyGiving/360-dei#2]
Currently we have a askedStatus field with several options.

It would be good to confirm the use cases that mean these are wanted, because if they are not we can remove some or all of these options and simplify this for everyone.

* Is it required to know if a question has been asked or not? Someone can of course look for data with no answer, but lack of an answer may be for one of 2 reasons (question was never asked or question was asked, they just didn't answer). Is it important to tell those 2 situations apart?

* If it's important to know if a question was not asked, is it also important to know why? This could be because the funder has decided not to use it (NOT_APPLICABLE) or because this is an old grant made before any DEI process was adopted (HISTORICAL_DATA). Is it important to tell the difference? Are there any other situations to consider?

* Is it important to know when a question was asked, during the application process or after?

**Comment by mrshll1001** [comment]
CLosing as I think we're happy with the current shape of the Asked Status codelist, which reflects the reasons a question may not be asked: not relevant, or this is historical data. It also reflects when a question was asked.

Thanks for your work on this James!

If there is a reply status of "Reply got", and no data, then we can assume that the data is either missing or the publisher has mis-labeled the reply status and it should be "No Reply" or "Reply got but no permissions" or "Reply general"
