### ISSUE TITLE
What options were available when a question was asked (available_options field)

### ISSUE THREAD

**Issue by ghost** [ThreeSixtyGiving/360-dei#3]
Currently we have a available_options field with several options.

It would be good to confirm the use cases that mean these are wanted, because if they are not we can remove this field and simplify this for everyone.

Is it important to know what options a person had a when filling out the form?

For example, you may analyse the data and say that only 30% of grants were targeted at a specific geographic area and the other 70% were then assumed to be over all areas, but if only 50% of people were given the option to specify a geography on their form then that's not an assumption you can make. In this case, having the available_options field is very useful. But is this an analysis that is needed?

**Comment by mrshll1001** [comment]
Closing as we understand this now: it's important to contextualise the answers by which options were available to people on the form. Especially being able to distinguish between where they've only been given e.g. categories as options rather than subcategories.
