### ISSUE TITLE
Reply recieved or private (reply_status field)

### ISSUE THREAD

**Issue by ghost** [ThreeSixtyGiving/360-dei#4]
Currently we have a reply_status field with several options - NO_REPLY, REPLY_GOT, REPLY_GOT_BUT_NO_PERMISSIONS

It would be good to confirm the use cases that mean these are wanted, because if they are not we can simplify this for everyone.

* Is it important to know if a question has been answered, if asked? (This is similar to #2). Someone can of course look for data with no answer, but lack of an answer may be for one of 2 reasons  (question was never asked or question was asked, they just didn't answer)  Is it important to tell those 2 situations apart?

* Is it important to know if someone went through the form process and pressed send but didn't select any answers? This would be revealed in the data by reply_status==REPLY_GOT but no answers actually being provided. 

* If someone gives an answer but does not allow the funder to make it public; should this be flagged in data?

This may be important if it is important to measure adoption by trying to answer questions like "how many people actually replied with data when asked too?".

**Comment by mrshll1001** [comment]
> If someone gives an answer but does not allow the funder to make it public; should this be flagged in data?

This is flagged in the data, because there may not be permission to share the underlying data as open data but the funder can include it in aggregated figures for analysis.

Closing, as this codelist is reflective of the use cases as far as we understand :-) Nice work, James.
