### ISSUE TITLE
General option - "This is general and is not aimed at or consists of a specific group of people"

### ISSUE THREAD

**Issue by ghost** [ThreeSixtyGiving/360-dei#5]
Can we confirm people should be able to select this option (if the funder lets them), and if so, no other fields (A taxonomy code, Geography, lived experience, prefer not to say) should be used at the same time?

**Comment by mrshll1001** [comment]
Confirmed, this is the intended behaviour. If there is a reply status of "Reply general" there should not be data in any other fields.
