### ISSUE TITLE
"Prefer not to say" option

### ISSUE THREAD

**Issue by ghost** [ThreeSixtyGiving/360-dei#6]
Can we confirm people should be able to select this option (if the funder lets them), and if so, no other fields (A taxonomy code, Geography, lived experience, general) should be used at the same time?

**Comment by mrshll1001** [comment]
Good spot for a data quality check.

Our understanding is that if this option is presented, then there may be a reply status of prefer not to say. The quality check should find all grants with this reply status and then flag those which then go on to contain data in the relevant response fields.
