### ISSUE TITLE
Add flag to indicate extension is being used

### ISSUE THREAD

**Issue by ghost** [ThreeSixtyGiving/360-dei#9]
There should be a flag in a data package that indicates this extension is being used.

We suggest, in a package, a new field "extensions". This is a string array. The value used should be: https://360-dei.readthedocs.io/en/latest/extension.json

This allows the concept of other extensions later, while not fully working up an extensions mechanism at this time.

We need to check this appears it the spreadsheet template properly.

**Comment by mrshll1001** [comment]
> We suggest, in a package, a new field "extensions". This is a string array. The value used should be: https://360-dei.readthedocs.io/en/latest/extension.json

This is being implemented as a draft proposal to the SC. If approved, there will be an `extensions` array added to the package schema where the values of this array are strings taken from a proposed extensions codelist. This allows 360Giving to control the extensions which will be added, in contrast to OCDS.

https://360-dei.readthedocs.io/en/latest/extension.json doesn't resolve. We are planning that the value `dei` is used to represent this extension.

**Comment by mrshll1001** [comment]
Closing as solved by [standard/pulls/361](https://github.com/ThreeSixtyGiving/standard/pull/361)
